### ISSUE TITLE
`hf mfu gen` has fixed inputs and is actually for mfc

### ISSUE THREAD

**Issue by micolous** [Proxmark/proxmark3#204]
Looking at `CmdHF14AMfuGenDiverseKeys`, this appears to be a key diversification function for MIFARE Classic, not MIFARE Ultralight.

Also, it appears to have fixed inputs, so it is not very useful in the present state.

**Comment by iceman1001** [comment]
You are right, its not useful at the moment.  That keydiv could also be used for the UL-C keys hence mfu because thats were I was trying to use it.  I'm thinking it could be used in Desfire but never gotten to it.
The interest is low because no-one seems to use NXP's diversification in their system so the cmd never got adapted for allround purposes. 

Feel free to contribute with enhancements.

**Comment by iceman1001** [comment]
Since no response in two months. I'm closing it.
