### ISSUE TITLE
CoreAnimation warning when exiting client on macOS

### ISSUE THREAD

**Issue by digitalentropy** [Proxmark/proxmark3#275]
When exiting the client on macOS 10.12.4 the following message is observed:

`CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces, or set CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 to abort when an implicit transaction isn't created on a main thread.`

Issue was first observed on 4/1 commits.

**Comment by pwpiwi** [comment]
This seems to be similar to the very old issue reported in http://www.proxmark.org/forum/viewtopic.php?id=1931
Also seen on Kali Linux, again with a different wording though.
Probably because QtApplication is created in one thread and destroyed in another thread (proxmark3.c). Someone familiar with Qt?
