### ISSUE TITLE
Segmentation fault on exit on Linux and osx

### ISSUE THREAD

**Issue by marshmellow42** [Proxmark/proxmark3#284]
Seems to be an issue with the exit routine and associated with the qt graphing code.
@holiman when you find a little time can you take a look?

**Comment by holiman** [comment]
Could do that, if I find some time. Any more info? Only when exiting, or at other times aswell ?

**Comment by marshmellow42** [comment]
Seems to only appear when sending the exit cmd  from the Pm3 cli

**Comment by marshmellow42** [comment]
ubuntu error example:
```user@ubuntuvm:~/master$ ./client/proxmark3 /dev/ttyACM0
ERROR: invalid serial port
proxmark3> exit
Segmentation fault (core dumped)
user@ubuntuvm:~/master$ 
```

**Comment by digitalentropy** [comment]
I can confirm on macOS 10.12.4 that the actual segfault appears only when exiting via the exit command.  When breaking via Ctrl-C the issue does not appear.

I have also observed that I can tell when it's going to happen because when executing the client the focus will be taken away from my command window and I have to manually click back into it.  Whenever things start off that way, exiting will result in a segfault.  If I don't notice the focus change, then I do not get a segfault.
