### ISSUE TITLE
"make" is broken

### ISSUE THREAD

**Issue by ikarus23** [Proxmark/proxmark3#36]
```
arm-none-eabi-gcc -c -I../include -I../common -Wall -Werror -pedantic -std=c99 -DWITH_LF -DWITH_ISO15693 -DWITH_ISO14443a -DWITH_ISO14443b -DWITH_ICLASS -DWITH_LEGICRF -DWITH_HITAG -I. -Os -mthumb-interwork -o obj/crapto1.o crapto1.c 
crapto1.c: In function 'quicksort':
crapto1.c:47:8: error: operation on '*it' may be undefined [-Werror=sequence-point]
    *it ^= (*it ^= *rit, *rit ^= *it);
        ^
crapto1.c:52:8: error: operation on '*rit' may be undefined [-Werror=sequence-point]
   *rit ^= (*rit ^= *start, *start ^= *rit);
        ^
crapto1.c: In function 'lfsr_rollback_bit':
crapto1.c:324:9: error: operation on 's->odd' may be undefined [-Werror=sequence-point]
  s->odd ^= (s->odd ^= s->even, s->even ^= s->odd);
         ^
cc1: all warnings being treated as errors
```
Sorry for not looking into that myself. Maybe one of you already know how to fix it. Or maybe I will have some time next week to look into it.

**Comment by holiman** [comment]
The problem, I think, is this:

     *rit ^= *it

If it is a pointer which hasn't been initialized, the compiler sees that the right hand side points to something undefined, so parenthesises doesn't matter. Also, an if-block is unseen by the compiler. 

The solution should be to initialize the pointer values. However, I don't get this problem when I build on linux 64 bit, which is a bit strange, no?

**Comment by marshmellow42** [comment]
No errors here on win 8.1

**Comment by ikarus23** [comment]
The issue with lines like
`*it ^= (*it ^= *rit, *rit ^= *it);`
is, that pointers/variables are changed twice within one sequence point.
This leads to undefined behavior. (Source: http://stackoverflow.com/a/10623165)

So if it's changed to
```
*it ^= *rit;
*it ^= (*rit ^= *it);
```
the errors are gone. And the code still does the same thing, right?!?

Personally I'm not a fan of the ,-operator and therefore not very familiar with it. I only like it for the initialization of variables or in for-loops with two indices. e.g.
```
int a = 2, b = 3;
for(i = 0, j = 10; i < 10; i++, j--)  {
    ... rest of loop ...
}

**Comment by ikarus23** [comment]
Ok, with using the ARM toolchain from the the Linux distribution I use (and not devkitARM) everything works fine...

But still, if someone can confirm that changing
```
*it ^= (*it ^= *rit, *rit ^= *it);
```
to
```
*it ^= *rit;
*it ^= (*rit ^= *it);
```
is safe, I will do that. Just for the code correctness.

**Comment by jaark** [comment]
It is an issue with the version of Devkitpro in use.

Using r43 (the current version) produces this error. Using r41 will allow the code to compile.

So there is a bug in either the PM code or the newer version of Devkit pro. Icouldn't say which though.

**Comment by pwpiwi** [comment]
>The issue with lines like
> ``` *it ^= (*it ^= *rit, *rit ^= *it); ```
>is, that pointers/variables are changed twice within one sequence point.
>This leads to undefined behavior. (Source: http://stackoverflow.com/a/10623165)

(should say "between two sequence points'" instead of "within one sequence point")

No, there is no undefined behaviour because the comma operator marks a sequence point.
Therefore this expression **is** equivalent to
```
*it ^= *rit;
*it ^= (*rit ^= *it);
```
`*it` is assigned only once in the first sequence. Both `*it` and `*rit` are assigned only once in the second sequence.

I would agree with @jaark that the compiler is wrong (has been upgraded to gcc 4.9.2 in devkitPro) and the warning is a false positive. However: what if `it` and `rit` are equal? Shouldn't the two line version then throw a warning too?

**Comment by ikarus23** [comment]
Thanks for clearing that up! It really looks like devkitPro is the one with the issue. Maybe *someone* should talk to a devkitPro developer and point this out... 

@pwpiwi
I don't get it... why should there be a warning it the `it` and `rit` are the same? and how should the compiler know at compile time if they will be the same?

**Comment by pwpiwi** [comment]
> I don't get it... why should there be a warning it the `it` and `rit` are the same? 

I am not sure and I am asking myself and others. If `it`and `rit` are the same (i.e. pointing to the same memory location) then the second line reduces to
```
*it ^= (*it ^= *it);
```
Here we indeed would assign twice to `*it` in one expression. Is the behaviour of this statement defined?

>  and how should the compiler know at compile time if they will be the same?

The compiler can't know. Which also means that the compiler cannot exclude that they are the same. Like with `if (a=b) ...`: the compiler can't know if this is by purpose but would throw a warning just to be sure.

**Comment by socram8888** [comment]
```c
*it ^= ( *it ^= *rit , *rit ^= *it);
```
Can be translated to:
```c
uint32_t x = *it;
*it = *rit;
*rit = x;
```
Why the programmer used the first one instead of the second one is a mistery to me, though.

**Comment by pwpiwi** [comment]
@socram8888 the XOR swap is a well known technique. It was very popular when processors had only a few registers and memory was low because it doesn't need an additional variable (register). It becomes more clear if it is written this way:
```
*rit = *rit ^ *it;
*it  = *it  ^ *rit;
*rit = *rit ^ *it;
```
This would eliminate the aliasing problem but would fail nevertheless if `it == rit`. I therefore think that the conventional swap with a temporary variable is safer, easier to comprehend and probably even more efficient with today's compilers and processors. 

(and the compiler was right to point us into that direction)

**Comment by socram8888** [comment]
I'd like to point out that I've found this repository by looking how to fix this very issue.

Since the author don't have apparently time anymore to update and fix issues in MFCUK, I have created today in GitHub a repository with that bug fixed, a few system-dependant optimizations, and a workaround for severe bug which caused a segmentation fault while parsing arguments using the getopt function from xgetopt.c under Cygwin

I have no idea if native Win32 builds are also affected by the last bug, because my workaround is to give system's getopt more priority over xgetopt, but Win32 has no built-in getopt. You can probably replicate it by running ```mfcuk -v 99``` which should cause the application to crash.

Repository is available here: https://github.com/socram8888/mfcuk, in case you want to take note of them

**Comment by ikarus23** [comment]
Ok, it's not only devkitPro. Newer releases of the [ARM version of gcc ](https://www.archlinux.org/packages/community/x86_64/arm-none-eabi-gcc/) (tested on Arch Linux) have the sames issue.

I think it's best if we change the affected lines to a style like this.
```c
uint32_t x = *it;
*it = *rit;
*rit = x;
```

**Comment by socram8888** [comment]
@ikarus23: that's exactly what I did in the repository I mentioned: https://github.com/socram8888/mfcuk/blob/7f90a420b6a35188bd0ce471c5cccda85e367d57/src/crypto1.c#L59

**Comment by ikarus23** [comment]
Fixed.
