### ISSUE TITLE
lf em 410xsim does not work

### ISSUE THREAD

**Issue by AuthorScX** [Proxmark/proxmark3#728]
Hi. my proxmark:
uC: AT91SAM7S256 Rev C          
Embedded Processor: ARM7TDMI          

bootrom: master/v3.1.0-21-g03439be-suspect 2018-11-29 14:43:59
os: master/v3.1.0-21-g03439be-suspect 2018-11-29 14:43:59
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/09/12 at 15:18:46

------------------
lf search
lf em 410xread
lf em 410xwrite
// -it's OK
but,
 lf em 410xsim- is not working.

 lf em 410xsim 740001BB0F
Starting simulating UID 740001BB0F  clock: 64          
Press pm3-button to abort simulation          
Sending [4096 bytes]#db# Stopped          
........
Starting to simulate            
// the "A" led is active, but no signal on antena    ( checked by oscilloscope  )
I was read #390...

**Comment by Fl0-0** [comment]
Hello,

On my proxmarks the EM Tag simulation work properly.
The A led is active during simulation.

I think it is normal that there is no signal on antenna because the proxmark is acting as a tag and do not generate the RF field.

Also, i have noticed that the Proxmark3 Easy (`AT91SAM7S256` is the MCU for old proxmarks and the Easy) has some issue simulating LF tags against some readers, but the RDV2 do not have any issue.
