### ISSUE TITLE
RDV4 Unable to capture cards in standalone mode.

### ISSUE THREAD

**Issue by Fughazii** [Proxmark/proxmark3#867]
Fresh out of the box, tested with multiple different RFID tags as well is multiple antennas (HF and LF).

[https://youtu.be/tGSCjqT-JKE](url)

**Comment by pwpiwi** [comment]
Some hints and remarks:
* This seems to be a "how to" question rather than a bug report. This kind of questions is better asked in the forum (http://www.proxmark.org/forum/index.php). You will have hundreds of users as an audience compared to a few developers.
* If you did not reflash your RDV 4 then your software is most probably not from this repository but from the RRG fork (https://github.com/RfidResearchGroup/proxmark3). If you don't get an answer from the forum then you should address your issue there.
* In standard configuration, the "SamyRun" standalone mode is active, which is LF only. The HF card therefore cannot work.
* The LF card which came with your package is most probably not programmed. I am not sure if SamyRun could read anything from it in its default configuration.
* This repository doesn't support standalone modes (the above mentioned historic SamyRun mode is an exception). If you need standalone modes then the RRG repository is better for you because it offers additional standalone modes.
